// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kegxwqlxytnbdbnejyrg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtlZ3h3cWx4eXRuYmRibmVqeXJnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEwNDQ2MTksImV4cCI6MjA2NjYyMDYxOX0.xq_wUiQjh524ihoNofMBSGjmU6A1t9fF_t2kEkZe_i8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);